WebShop/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity.Validation;
using System.Web.Mvc;
using WebShop.Models;
using WebShop.Models.DAL;

namespace WebShop.Controllers
{
    [Authorize]
    public class ItemController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();
        IUnitOfWork unit;
        public ItemController(IUnitOfWork unitIn)
        {
            unit = unitIn;
        }
        public ItemController()
        {
            unit = new UnitOfWork(context);
        }
        [Authorize(Roles = "Manager")]
        public ActionResult Index()
        {
            

            return View("Index");
        }
       
        public JsonResult Get()
        {
          
            var Items = unit.GetItems.Get()
                .Select( i=>new {
                    Category=i.Category,
                    Code = i.Code,
                    Name =i.Name,
                    Price = i.Price,
                    Id = i.Id
                });
            return Json(new {Data=Items},JsonRequestBehavior.AllowGet);
        }
        
        public ActionResult GetWithoutOrderView()
        {

            return View("GetWithoutOrderView");
        }
        
       /* public JsonResult GetWithoutOrder()
        {
         
            var Items = unit.GetItems.Get().Select(i => new { 
                Id=i.Id,
               Code=i.Code,
               Name=i.Name,
               Price = i.Price,
               Category = i.Category    }).ToArray();
           
            return Json(new { Data = Items }, JsonRequestBehavior.AllowGet);
        }*/
        [HttpPost]
        [Authorize(Roles = "Manager")]
        public JsonResult Delete(String Id)
        {
          
           
            
            try
            {
                unit.GetItems.DeleteById(Guid.Parse(Id));
                unit.Save();
            }
            catch (Exception ex)
            {
                return Json(new { Msg = ex.Message, success = false }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { Data = Id, success = true }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        [Authorize(Roles = "Manager")]
        public JsonResult Create(string Code, string Name, decimal Price, string Category)
        {
            Item item = new Item();
            item.Category = Category;
            item.Code = Code;
            item.Name = Name;
            item.Price = Price;
            item.Id = Guid.NewGuid();
            try
            {
                unit.GetItems.Insert(item);
                unit.Save();
            }
            catch (Exception ex)
            {
                return Json(new { Msg = ex.Message, success = false }, JsonRequestBehavior.AllowGet);
            }
            return  Json(new { Data = item ,success = true}, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        [Authorize(Roles = "Manager")]
        public JsonResult Update(Item item)
        {
           
            Item ItemOld = unit.GetItems.GetByID(item.Id);
            if (ItemOld != null)
            {
                ItemOld.Category = item.Category;
                ItemOld.Code = item.Code;
                ItemOld.Name = item.Name;
                ItemOld.Price = item.Price;
                unit.GetItems.Update(ItemOld);
               
            }
            try
            {
                unit.Save();
            }
            catch (Exception ex)
            {
                return Json(new { Msg = ex.Message, success = false }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { Data = ItemOld, success = true }, JsonRequestBehavior.AllowGet);
        }
        
    }
}

WebShop/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebShop.Models.DAL;
using WebShop.Models;
using System.Web.Mvc;

namespace WebShop.Controllers
{
    [Authorize]
    public class OrderController : UserController
    {
        ApplicationDbContext context = new ApplicationDbContext();
        IUnitOfWork unit;
        public OrderController(IUnitOfWork unitIn)
        {
            unit = unitIn;
        }
        public OrderController()
        {
            unit = new UnitOfWork(context);
        }
        public ActionResult UserOrderView()
        {
            return View();

        }
        [Authorize(Roles = "Manager")]
        public ActionResult ManagerOrderView()
        {
            return View();

        }
        
        public JsonResult GetOrderWithItems()
        {
           
            Customer customer =  unit.GetCustomers.Get()
                .Where(c => c.Name == HttpContext.User.Identity.Name).FirstOrDefault();
            var OrdersAndItems = GetAllOrderWithItems(unit, customer.Id);
            return Json(new { Data = OrdersAndItems.ToArray() }, JsonRequestBehavior.AllowGet);
        }
       
        IEnumerable<dynamic> GetAllOrderWithItems(IUnitOfWork unit, Guid UserId, string UserName = null)
        {
            Func<dynamic, dynamic> deleg;
            if (String.IsNullOrEmpty(UserName))
            {
                deleg = o => new
                {
                    Items = unit.GetElementOfOrders.Get()
                      .Where(e => e.OrderId == o.Id).Select(s => new
                      {
                          Code = s.Item.Code,
                          Category = s.Item.Category,
                          Name = s.Item.Name,
                          Price = s.Item.Price,
                          Id = s.Item.Id,
                          Number = s.ItemCount
                      }).ToArray(),
                    OrderDate = o.OrderDate.ToShortDateString(),
                    OrderNumber = o.OrderNumber,
                    ShipmentDate = o.ShipmentDate == null? String.Empty : o.ShipmentDate.ToShortDateString(),
                    Status = o.Status,
                    Id = o.Id
                };
            }
            else
            {
                deleg = o => new
                {
                    UserName = UserName,
                    Items = unit.GetElementOfOrders.Get()
                      .Where(e => e.OrderId == o.Id).Select(s => new
                      {
                          Code = s.Item.Code,
                          Category = s.Item.Category,
                          Name = s.Item.Name,
                          Price = s.Item.Price,
                          Id = s.Item.Id,
                          ItemCount = s.ItemCount
                      }).ToArray(),
                    OrderDate = o.OrderDate.ToShortDateString(),
                    OrderNumber = o.OrderNumber,
                    ShipmentDate = o.ShipmentDate==null?String.Empty: o.ShipmentDate.ToShortDateString(),
                    Status = o.Status,
                    Id = o.Id
                };
            }
            var OrdersAndItems = unit.GetOrders.Get()
                    .Where(o => o.CustomerId == UserId)
                    .Select(deleg);
            return OrdersAndItems.ToArray();
        }
        [Authorize(Roles = "Manager")]
        public JsonResult GetOrdersForManager()
        {
         
            var AllOrderWithItems = unit.GetCustomers.Get()
                .SelectMany(s=>GetAllOrderWithItems(unit, s.Id, s.Name).ToArray());

            return Json(new { Data = AllOrderWithItems.ToArray() }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        [Authorize(Roles = "Manager")]
        public JsonResult Close(string Id)
        {
            
            Guid GuidId = Guid.Parse(Id);
            Order order = unit.GetOrders.GetByID(GuidId);
            if (order.Status == StatusOrder.New)
                return Json(new { success = false, Msg = "Заказ должен быть сначала подтвержден!" }, JsonRequestBehavior.AllowGet);
            order.Status = StatusOrder.Complete;
            unit.Save();
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        [Authorize(Roles = "Manager")]
        public JsonResult Confirm(string Id, DateTime Date)
        {
         
            Guid GuidId = Guid.Parse(Id);
            Order order = unit.GetOrders.GetByID(GuidId);
            if (order.Status == StatusOrder.Complete)
                return Json(new { success = false,Msg = "Данный заказ уже выполнен.Его нельзя подтвердить!"  }, JsonRequestBehavior.AllowGet);
            order.ShipmentDate = Date;
            order.Status = StatusOrder.Confirm;
            unit.Save();
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }
      
        [HttpPost]
    
        public JsonResult Create( string Address, Item[] Items, Int32[] Numbers)
        {
          
            Order order = new Order();
            order.ShipmentDate =null ;
            order.OrderDate = DateTime.Now;
            order.Status = StatusOrder.New;
            order.Id = Guid.NewGuid();
            Customer customer = unit.GetCustomers.Get()
                .Where(c => c.Name == HttpContext.User.Identity.Name).FirstOrDefault();
            order.CurrentCustomer = customer;
            order.CustomerId = customer.Id;
            customer.CollectionOrders = new List<Order>();
            order.ElementOfOrders = new List<ElementOfOrder>();
            customer.CollectionOrders.Add(order);
          
            for (int i = 0; i != Items.Length; i++)
            {
                ElementOfOrder element = new ElementOfOrder();
                Item item = unit.GetItems.GetByID(Items[i].Id); 

                element.Id = Guid.NewGuid();
                element.ItemCount = Numbers[i];
                element.ItemId = Items[i].Id;
                element.ItemPrice = Items[i].Price;
                
                element.Item = item;
                item.ElementOfOrders.Add(element);

                element.OrderId = order.Id;
                element.CurrentOrder = order;
                order.ElementOfOrders.Add(element);
                
                unit.GetItems.Update(item);
                unit.GetElementOfOrders.Insert(element);

            }
            unit.GetOrders.Insert(order);
            unit.GetCustomers.Update(customer);
            unit.Save();
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        public JsonResult Delete(string id)
        {
            Guid Id = Guid.Parse(id);
          
            try
            {
                Order order = unit.GetOrders.Get().Where(o => o.Id == Id).FirstOrDefault();
                Delete(order, unit);
            }
            catch(Exception ex)
            {
                return Json(new { success = false, Msg = ex.Message });
            }
            return Json(new { success = true });
        }
       
    }
}

WebShop/Views/Order/UserOrderView.cshtml
@{
    ViewBag.Title = "UserOrderView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    Ext.onReady(function () {
        Ext.define('Items', {
            extend: 'Ext.data.Model',

            idProperty: 'CartID',

            fields: [{
                name: 'Code',
                type: 'string'
            }, {
                name: 'Category',
                type: 'string'
            }, {
                name: 'Name',
                type: 'string'
            }, {
                name: 'Price',
                type: 'int'
            },
             {
                 name: 'Number',
                 type: 'int'
             },
            {
                name: 'Id',
                type: 'string'
            }]
        });
        var StoreMemory = Ext.create('Ext.data.Store', {
            model: 'Items',
            proxy: {
                type: 'memory',
                reader:
                    {
                        type: 'json'
                    }
            }
        });
        var ItemsInOrderGrid = Ext.create('Ext.grid.Panel', {
            height: 300,
            title: 'Корзина',
            store: StoreMemory,
            flex: 1,
            margin: '0 0 0 10',
            columns: [{
                header: 'Код товара',
                dataIndex: 'Code'
            }, {
                header: 'Наименование товара',
                dataIndex: 'Name'
            }, {
                header: 'Цена',
                dataIndex: 'Price',
                flex: 1
            }, {
                header: 'Категория товара',
                dataIndex: 'Category',
                flex: 1
            }, {
                header: 'Количество',
                dataIndex: 'Number',
                flex: 1
            }]
        });
        Ext.define('Order', {
            extend: 'Ext.data.Model',

            idProperty: 'orderID',

            fields: [{
                name: 'OrderDate',
                type: 'string'
                
            }, {
                name: 'ShipmentDate',
                type: 'string'
            }, {
                name: 'Status',
                type: 'string'
            }, {
                name: 'OrderNumber',
                type: 'int'
            },
            {
                name: 'Items',
                type:'auto'
            },,
            {
                name: 'Id',
                type: 'string'
            }]
        });
   

        var StoreOrder = Ext.create('Ext.data.Store', {
            model: 'Order',
            autoLoad: true,
            proxy: {
                type: 'ajax',
                api:
                    {

                        read: '/Order/GetOrderWithItems'
                    },
                reader:
                    {

                        idProperty: 'Id',
                        type: 'json',
                        root: 'Data'
                    }
            }
        });
        var OrderGrid = Ext.create('Ext.grid.Panel',  {
            height: 300,
            title: 'Заказы',
            store: StoreOrder,
            flex: 1,
            margin: '0 0 0 10',
            columns: [{
                header: 'Дата создания',
                dataIndex: 'OrderDate'
            }, {
                header: 'Дата доставки',
                dataIndex: 'ShipmentDate'
            }, {
                header: 'Статус',
                dataIndex: 'Status',
                flex: 1
            }, {
                header: 'Номер заказа',
                dataIndex: 'OrderNumber',
                flex: 1
            }/*, {
                header: 'Id',
                dataIndex: 'Id',
                flex: 1
            }*/],
            listeners:
                {
                    select: function (record, index, eOpts) {
                        ItemsInOrderGrid.getStore().removeAll();
                        ItemsInOrderGrid.getStore().loadData(this.getSelectionModel().getSelection()[0].get('Items'));
                    }
                },
            fbar: ['->', {
                xtype: 'button',
                text: 'Удалить  заказ',
                width: 200,
                margin: '5 0 0 5',
                listeners:
                {
                    click: function ()
                    {
                        if (OrderGrid.getSelectionModel().getCount() > 0)
                        {
                            var Status = OrderGrid.getSelectionModel().getSelection()[0].get('Status');
                            if (Status != 'Новый')
                            {
                                Ext.MessageBox.alert('Удаление заказа', 'Можно удалить заказы только имеющие статус "Новый"!');
                                return;
                            }
                            var sndObject = new Object();
                            sndObject.Id = OrderGrid.getSelectionModel().getSelection()[0].get('Id');
                            
                           
                            Ext.Ajax.request({
                                method: 'POST',
                                url: '/Order/Delete',
                                headers: {
                                    'Content-Type': 'application/json; charset=utf-8'
                                },
                                params: {


                                },
                                jsonData: Ext.JSON.encode(sndObject),
                                success: function (response) {
                                    var jsonData = Ext.JSON.decode(response.responseText);
                                    if (jsonData.success == true) {

                                        OrderGrid.getStore().remove(OrderGrid.getSelectionModel().getSelection()[0]);
                                        ItemsInOrderGrid.getStore().removeAll();
                                        Ext.MessageBox.alert('Удаление заказа', 'Заказ был успешно удален!');
                                    }
                                
                                }
                                //          scope: this,
                                //            jsonData: sndData
                            });
                        }
                        else 
                            Ext.MessageBox.alert('Предупреждение', 'Выберете отменяемый заказ!');
                    }
                }
            }]
        });
       
        var MainPanel = Ext.create('Ext.panel.Panel',
           {
               width: '100%',
               height: 200,
               layout: {
                   type: 'hbox',
                   align: 'stretch'
               },
               items: [OrderGrid, ItemsInOrderGrid],
               renderTo: 'OrderTableUser'

           });
    });
</script>
<div class="container">
    <ul>
        <li class="one">@Html.ActionLink("About", "Index", "Home")</li>
        <!--
        -->
        <li class="two">@Html.ActionLink("Каталог товаров", "GetWithoutOrderView", "Item")</li>
        <!--
        -->
        <li class="three">@Html.ActionLink("Мои заказы", "UserOrderView", "Order")</li>
        <hr class="threehr" />
    </ul>
</div>
<div id="OrderTableUser"></div>